[package]
name = "fccore"
version = "0.0.1"
authors = [ "Blake Loring <blake_l@parsed.uk>" ]

[dependencies]
time = "*"
rustc-serialize = "*"
piphysical = { git = "https://github.com/jawline/PiPhysical.git" }
simplelog = { git = "https://github.com/jawline/SimpleLog.git" }